version: '2'
services:
    graphql:
        container_name: croupier
        image: 121364511741.dkr.ecr.us-east-1.amazonaws.com/frontent:latest
        restart: always
        environment:
            - READ_NODE_ENV=production

networks:
    redis:
        external: true
